version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: .
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=${SQLALCHEMY_DATABASE_URI}
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}